GET http://localhost:5000/api/auth/users

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Max",
    "email": "example@gamil.com",
    "password": "password"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "example@gamil.com",
    "password": "password"
}